// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RegistroDePaqueteEPS.DAL;

#nullable disable

namespace RegistroDePaqueteEPS.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20251124013457_Tercera")]
    partial class Tercera
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("RegistroDePaqueteEPS.Models.Paquetes", b =>
                {
                    b.Property<int>("PaqueteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ClienteId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CondicionEspecial")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Contenido")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NumeroRecepcion")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("TEXT")
                        .HasComputedColumnSql("'MIO' || printf('%08d', PaqueteId)");

                    b.Property<string>("NumeroTracking")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Peso")
                        .HasColumnType("REAL");

                    b.Property<bool>("Retenido")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Suplidor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Total")
                        .HasColumnType("REAL");

                    b.HasKey("PaqueteId");

                    b.ToTable("Paquetes");
                });

            modelBuilder.Entity("RegistroDePaqueteEPS.Models.Preavisos", b =>
                {
                    b.Property<int>("PreavisoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClienteId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Contenido")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<string>("NumeroTracking")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Tienda")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Transportista")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Valor")
                        .HasColumnType("REAL");

                    b.HasKey("PreavisoId");

                    b.ToTable("Preavisos");
                });
#pragma warning restore 612, 618
        }
    }
}
