// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RegistroDePaqueteEPS.DAL;

#nullable disable

namespace RegistroDePaqueteEPS.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20251124040906_Quinta")]
    partial class Quinta
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("RegistroDePaqueteEPS.Models.AutorizadosEntrega", b =>
                {
                    b.Property<int>("AutorizadoEntregaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClienteId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Identificacion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("AutorizadoEntregaId");

                    b.ToTable("AutorizadosEntrega");
                });

            modelBuilder.Entity("RegistroDePaqueteEPS.Models.DireccionesDelivery", b =>
                {
                    b.Property<int>("DireccionDeliveryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AutorizadoEntregaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Calle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ClienteId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Domicilio")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Municipio")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Principal")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Provincia")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Referencias")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Sector")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("DireccionDeliveryId");

                    b.ToTable("DireccionesDelivery");
                });

            modelBuilder.Entity("RegistroDePaqueteEPS.Models.Paquetes", b =>
                {
                    b.Property<int>("PaqueteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ClienteId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CondicionEspecial")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Contenido")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NumeroRecepcion")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("TEXT")
                        .HasComputedColumnSql("'MIO' || printf('%08d', PaqueteId)");

                    b.Property<string>("NumeroTracking")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Peso")
                        .HasColumnType("REAL");

                    b.Property<bool>("Retenido")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Suplidor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Total")
                        .HasColumnType("REAL");

                    b.HasKey("PaqueteId");

                    b.ToTable("Paquetes");
                });

            modelBuilder.Entity("RegistroDePaqueteEPS.Models.Preavisos", b =>
                {
                    b.Property<int>("PreavisoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClienteId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Contenido")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<string>("NumeroTracking")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Tienda")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Transportista")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Valor")
                        .HasColumnType("REAL");

                    b.HasKey("PreavisoId");

                    b.ToTable("Preavisos");
                });
#pragma warning restore 612, 618
        }
    }
}
